services:
  - type: web
    name: ecommerce
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
    plan: free
    buildFilter:
      paths:
        - .
    preDeployCommand: python manage.py migrate
