services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
    buildFilter:
      paths:
        - ecommerce/*
    preDeployCommand: python manage.py migrate
