# Generated by Django 5.1.5 on 2025-02-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_sellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='selleradd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('shopname', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
