# Generated by Django 5.1.5 on 2025-02-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_alter_selleradd_sellername_addproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleradd',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='shopname',
            field=models.CharField(max_length=255),
        ),
    ]
