# Generated by Django 5.1.5 on 2025-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_alter_selleradd_email_alter_selleradd_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleradd',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
