# Generated by Django 5.1.5 on 2025-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_alter_selleradd_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='category',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
