# Generated by Django 5.1.5 on 2025-02-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_addproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='seller',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
