# Generated by Django 5.1.5 on 2025-02-21 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_addproduct_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='stock',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='phonenumber',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='sellername',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='shopname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='sellers',
        ),
    ]
