# Generated by Django 5.1.5 on 2025-02-21 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_alter_addproduct_stock_alter_selleradd_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='seller',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='sellername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.selleradd'),
            preserve_default=False,
        ),
    ]
