# Generated by Django 5.1.5 on 2025-02-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_remove_addproduct_seller_addproduct_sellername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='sellername',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
