# Generated by Django 5.1.5 on 2025-02-21 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_alter_addproduct_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.selleradd'),
            preserve_default=False,
        ),
    ]
