# Generated by Django 5.1.5 on 2025-02-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0017_alter_addproduct_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleradd',
            old_name='sellername',
            new_name='seller_id',
        ),
    ]
