# Generated by Django 5.1.5 on 2025-02-21 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0018_rename_sellername_selleradd_seller_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='seller',
        ),
        migrations.CreateModel(
            name='sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('shopname', models.CharField(max_length=255, unique=True)),
                ('phonenumber', models.CharField(max_length=15, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('sellername', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='addproduct',
            name='sellername',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adm.sellers'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='selleradd',
        ),
    ]
