# Generated by Django 5.1.5 on 2025-02-21 05:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0019_remove_addproduct_seller_sellers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellers',
            new_name='selleradd',
        ),
    ]
