# Generated by Django 5.1.5 on 2025-02-21 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0020_rename_sellers_selleradd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='selleradd',
            new_name='sellertable',
        ),
    ]
