# Generated by Django 5.1.5 on 2025-02-21 05:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0021_rename_selleradd_sellertable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellertable',
            new_name='selleradd',
        ),
    ]
