# Generated by Django 5.1.5 on 2025-02-21 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0022_rename_sellertable_selleradd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='sellername',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adm.selleradd'),
        ),
    ]
