# Generated by Django 5.1.5 on 2025-02-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0023_alter_addproduct_sellername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='sellername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.selleradd'),
        ),
    ]
