# Generated by Django 5.1.5 on 2025-02-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0027_addproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addproducts',
        ),
    ]
