# Generated by Django 5.1.5 on 2025-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0028_delete_addproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleradd',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
