# Generated by Django 5.1.5 on 2025-02-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0029_selleradd_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleradd',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
