# Generated by Django 5.1.5 on 2025-02-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0030_alter_selleradd_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_id',
            field=models.CharField(default=111, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
