# Generated by Django 5.1.5 on 2025-02-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0031_addproduct_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='product_id',
        ),
    ]
