# Generated by Django 5.1.5 on 2025-02-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0035_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
