# Generated by Django 5.1.5 on 2025-02-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0036_addproduct_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
