# Generated by Django 5.1.5 on 2025-02-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0037_delete_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleradd',
            old_name='profileimage',
            new_name='profile',
        ),
    ]
