# Generated by Django 5.1.5 on 2025-02-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0039_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='customer_id',
        ),
    ]
