# Generated by Django 5.1.5 on 2025-02-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0040_remove_customers_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('sellername', models.CharField(max_length=100)),
                ('shopname', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_number', models.CharField(max_length=140)),
                ('delivery_address', models.CharField(max_length=130)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.addproduct')),
            ],
        ),
    ]
