# Generated by Django 5.1.5 on 2025-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0041_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='product_id',
            field=models.CharField(max_length=200),
        ),
    ]
