# Generated by Django 5.1.5 on 2025-07-26 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0042_alter_orderlist_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(default='No description available', upload_to='product_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='profile',
            field=models.ImageField(default='No profile available', upload_to='seller_profiles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='shopname',
            field=models.CharField(max_length=100),
        ),
    ]
