# Generated by Django 5.1.5 on 2025-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0043_remove_role_description_orderlist_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
    ]
