# Generated by Django 5.1.5 on 2025-07-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0044_alter_addproduct_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleradd',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
