# Generated by Django 5.1.5 on 2025-07-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0045_alter_selleradd_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='product_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='selleradd',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
